name: Docs
on: { release: { types: [ created ] } }
permissions: { contents: read, pages: write, id-token: write }

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v4, with: { node-version: ^18.20 || ^20.10 || >=22 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { version: ^9, run_install: true } }
    - { name: direnv action, uses: HatsuneMiku3939/direnv-action@v1 }
    - run: typedoc --options typedoc.json src/*.ts src/**/*.ts
    - { name: Upload GitHub Pages artifact, uses: actions/upload-pages-artifact@v3, with: { path: docs } }
    - { name: Deploy GitHub Pages site, uses: actions/deploy-pages@v4 }
